# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(unique=True)),
                ('universal_intension', models.CharField(max_length=2047)),
                ('evangelisation_intension', models.CharField(max_length=2047)),
                ('pcm_intension', models.CharField(max_length=2047)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mystery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('group', models.CharField(choices=[('joyful', 'Joyful Mysteries'), ('luminous', 'Luminous Mysteries'), ('sorrowful', 'Sorrowful Mysteries'), ('glorious', 'Glorious Mysteries')], max_length=15)),
                ('number', models.SmallIntegerField(unique=True)),
                ('image_path', models.ImageField(upload_to=b'')),
                ('quote', models.TextField()),
                ('meditation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonIntension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=63, unique=True)),
                ('intension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosary.Intension')),
                ('mystery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosary.Mystery')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosary.Person')),
            ],
        ),
    ]
