# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rosary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intension',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='intension',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mystery',
            name='group',
            field=models.CharField(choices=[('luminous', 'Luminous Mystery'), ('sorrowful', 'Sorrowful Mystery'), ('joyful', 'Joyful Mystery'), ('glorious', 'Glorious Mystery')], max_length=15),
        ),
    ]
