# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosary', '0002_auto_20161027_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intension',
            name='evangelisation_intension',
            field=models.TextField(max_length=2047),
        ),
        migrations.AlterField(
            model_name='intension',
            name='pcm_intension',
            field=models.TextField(max_length=2047),
        ),
        migrations.AlterField(
            model_name='intension',
            name='universal_intension',
            field=models.TextField(max_length=2047),
        ),
        migrations.AlterField(
            model_name='mystery',
            name='group',
            field=models.CharField(choices=[('luminous', 'Tajemnica \u015awiat\u0142a'), ('sorrowful', 'Tajemnica Bolesna'), ('joyful', 'Tajemnica Radosna'), ('glorious', 'Tajemnica Chwalebna')], max_length=15),
        ),
    ]
