# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosary', '0003_auto_20161114_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intension',
            old_name='universal_intension',
            new_name='papal_intension',
        ),
    ]
