# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosary', '0004_auto_20170112_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intension',
            name='evangelisation_intension',
            field=models.TextField(blank=True, max_length=2047, null=True),
        ),
    ]
