# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosary', '0005_auto_20170126_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystery',
            name='group',
            field=models.CharField(choices=[('luminous', 'Luminous Mystery'), ('sorrowful', 'Sorrowful Mystery'), ('joyful', 'Joyful Mystery'), ('glorious', 'Glorious Mystery')], max_length=15),
        ),
    ]
