# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosary', '0007_auto_20171115_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='language',
            field=models.CharField(default='pl-pl', max_length=7),
        ),
        migrations.AlterField(
            model_name='mystery',
            name='group',
            field=models.CharField(choices=[('luminous', 'Tajemnica \u015awiat\u0142a'), ('sorrowful', 'Tajemnica Bolesna'), ('joyful', 'Tajemnica Radosna'), ('glorious', 'Tajemnica Chwalebna')], max_length=15),
        ),
    ]
